# toolchain.toml
[toolchain]
channel = "stable"
components = [ "rustfmt", "rust-src", "cargo", "rustc"]
targets = ["x86_64-unknown-linux-gnu", "armv7-unknown-linux-gnueabihf", "aarch64-unknown-linux-gnu"]
profile = "minimal"
